### ISSUE TITLE
Re-evaluate the `Evaluate` trait

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-boolean-functions#10]
I'd prefer `evaluate`, `evaluate_checked` and `evaluate_with_default` (with the option to set the default value for unknown variables) in the `Evaluate` trait. Setting unknown variables to `false` by default is a great way to amplify small bugs into hard to detect bugs. This would also affect `evaluate_safe` and `evaluate_nonsafe`. To a Python user, safe and nonsafe will be likely very foreign. We need to have a default evaluate method here (that can be also used to implement __call__) and throws an exception, and then `evaluate_with_default` in case they want a method that never fails. I'll prepare a PR for this.

**Comment by AurumTheEnd** [comment]
Note to self:

`evaluate`: use false as default value if literal is not found

`evaluate_checked`: return Err if literal is not found

`evaluate_with_default`: pass default value if literal is not found
