### ISSUE TITLE
Consider alternative `Expression` design

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-boolean-functions#12]
I now believe that the type that we actually want for the expression is `Expression(Arc<ExpressionData>)` and then have a private `enum ExpressionData { ... }` with all the variants that we have now (using `Expression` instead of `Arc<Expression>` inside). That way, we can make methods like `Expression.rename_literals` that return a new expression when the content actually changed, and simply clone the `Arc` counter if the expression did not change. We could even consider just making `Expression` implement `Copy` and live with that. An obvious issue is that we cannot pattern-match on this. But maybe if the enum was actually public, we could still expose it's reference with something like `expression.data()` and pattern match on that. I am sorry it took me so long to realize this. I'll make a prototype to see if this is actually as useful as I think it might be.

**Comment by AurumTheEnd** [comment]
Implemented in #15.
