### ISSUE TITLE
Formalize the notion of equivalence on functions vs. representations

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-boolean-functions#4]
In theory, every representation of a Boolean function can be compared "syntactically" to check for equality. If two functions are syntactically equal, they are also semantically equal (they compute the same thing). However, except for function tables and BDDs in some special cases, a function can have different syntactic representation with the same semantics. Furthermore, there is no way to check syntactic equivalence between two functions in different representations, but the semantic equivalence still exists even there.

As such, we need to plan our API in such a way that it is (a) clear which equality checks are meant to be syntactic and which are meant to be semantic; (b) the user has the option to consider both depending on their needs (i.e. syntactic or semantic on the same representation, and semantic on different representations, possibly with a default "not equal" for syntactic equality of different representations).

**Comment by AurumTheEnd** [comment]
Semantic checks are done with the SemanticEq trait's methods, syntactic checks are through the Eq trait. Neither allow to check between different implementations.

**Comment by AurumTheEnd** [comment]
Semantic checks are done with the SemanticEq trait's methods, syntactic checks are through the Eq trait. Neither allow to check between different implementations.
